# Generated by Django 4.2 on 2023-08-05 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_medi_info_caution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guaName', models.CharField(max_length=20)),
                ('guaRelation', models.CharField(max_length=100)),
                ('guaPhone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.medi_info')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fam_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('famRelation', models.CharField(max_length=100)),
                ('famDiag', models.CharField(max_length=100)),
                ('famBirth', models.DateField()),
                ('famDeath', models.DateField(blank=True, null=True)),
                ('famDReason', models.CharField(blank=True, max_length=50, null=True)),
                ('info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.medi_info')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docHospital', models.CharField(max_length=100)),
                ('docMajor', models.CharField(max_length=100)),
                ('docName', models.CharField(max_length=20)),
                ('docSign', models.ImageField(upload_to='')),
                ('docFile', models.ImageField(upload_to='')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('diagDate', models.DateField()),
                ('diagRegi', models.CharField(max_length=50)),
                ('diagNum', models.CharField(max_length=50)),
                ('diagMajor', models.CharField(max_length=100)),
                ('diagMajCode', models.CharField(max_length=100)),
                ('diagTF', models.BooleanField(default=False)),
                ('diagMinor', models.CharField(max_length=300)),
                ('diagMinCode', models.CharField(max_length=300)),
                ('diagInitDate', models.DateField()),
                ('diagIn', models.DateField()),
                ('diagOut', models.DateField()),
                ('diagUSage', models.CharField(blank=True, max_length=50, null=True)),
                ('diagETC', models.TextField()),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.doctor')),
                ('info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.medi_info')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
