# Generated by Django 4.2 on 2023-08-05 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_guardian_fam_history_doctor_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='diagMemo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagETC',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='medi_info',
            name='patAddress',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surChartNum', models.CharField(max_length=50)),
                ('surWriter', models.CharField(max_length=20)),
                ('surDate', models.DateField()),
                ('surNum', models.IntegerField()),
                ('surHospital', models.CharField(max_length=100)),
                ('surField', models.CharField(max_length=300)),
                ('surOper', models.CharField(max_length=20)),
                ('surAssi', models.CharField(max_length=20)),
                ('surAnesDoc', models.CharField(max_length=20)),
                ('surName', models.CharField(max_length=100)),
                ('surCode', models.CharField(max_length=50)),
                ('surPreDiag', models.CharField(max_length=100)),
                ('surPostDiag', models.CharField(max_length=100)),
                ('surAnes', models.CharField(max_length=100)),
                ('surEvent', models.BooleanField(default=False)),
                ('surRemoval', models.BooleanField(default=False)),
                ('surBloodTrans', models.BooleanField(default=False)),
                ('surPre', models.TextField(default='')),
                ('surDur', models.TextField(default='')),
                ('surPost', models.TextField(default='')),
                ('surTube', models.BooleanField(default=False)),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('diag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.diagnosis')),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.doctor')),
                ('info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.medi_info')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prePharm', models.CharField(max_length=100)),
                ('preAddress', models.CharField(max_length=200)),
                ('preDate', models.DateField()),
                ('preChem', models.CharField(max_length=20)),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('diag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.diagnosis')),
                ('info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.medi_info')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediName', models.CharField(max_length=100)),
                ('mediEffect', models.CharField(max_length=300)),
                ('mediDetail', models.CharField(max_length=100)),
                ('mediCode', models.CharField(max_length=100)),
                ('mediUnit', models.CharField(max_length=50)),
                ('mediAmount', models.CharField(max_length=50)),
                ('mediCount', models.CharField(max_length=50)),
                ('mediPeriod', models.CharField(max_length=50)),
                ('diag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.diagnosis')),
                ('info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.medi_info')),
                ('pre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.prescription')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
